CLZ.Solution/CLZ/Controllers/SysModuleController.cs
using CLZ.CLZService;
using CLZ.Common;
using CLZ.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CLZ.Controllers
{
    public class SysModuleController : BaseController
    {
        //
        // GET: /SysModuleOperate/
        [SupportFilter]
        public ActionResult Index()
        {
            ViewBag.Perm = GetPermission();
            return View();
        }

        /// <summary>
        /// 获取列表
        /// </summary>
        /// <param name="pager">分页</param>
        /// <param name="queryStr">查询条件</param>
        /// <returns></returns>
        [SupportFilter(ActionName = "Index")]
        [HttpPost]
        public JsonResult GetList(string id)
        {
            try
            {
                CommonServiceClient client = new CommonServiceClient();
                if (id == null)
                    id = "0";
                List<SysModule> list = client.GetModuleByParentId(id);
                var json = from r in list
                           select new 
                           {
                               Id = r.Id,
                               Name = r.Name,
                               EnglishName = r.EnglishName,
                               ParentId = r.ParentId,
                               Url = r.Url,
                               Iconic = r.Iconic,
                               Sort = r.Sort,
                               Remark = r.Remark,
                               Enable = r.Enable,
                               CreatePerson = r.CreatePerson,
                               CreateTime = r.CreateTime,
                               IsLast = r.IsLast,
                               state = (client.GetModuleByParentId(r.Id).Count > 0) ? "closed" : "open"
                           };
                return Json(json);
            }
            catch (Exception ex)
            {
                ExceptionHelper.WriteException(ex);
                throw ex;
            }
            
        }
        [HttpPost]
        [SupportFilter(ActionName = "Index")]
        public JsonResult GetOptListByModule(GridPager pager, string mid)
        {
            pager.rows = 1000;
            pager.page = 1;
            CommonServiceClient client = new CommonServiceClient();
            List<SysModuleOperate> list = client.GetModuleOperateList(ref pager, mid);
            var json = new
            {
                total = pager.totalRows,
                rows = list

            };

            return Json(json);
        }


        #region 创建模块
        [SupportFilter]
        public ActionResult Create(string id)
        {
            ViewBag.Perm = GetPermission();
            SysModule entity = new SysModule()
            {
                ParentId = id,
                Enable = true,
                Sort = 0
            };
            return View(entity);
        }

        [HttpPost]
        [SupportFilter]
        public JsonResult Create(SysModule model)
        {
            CommonServiceClient client = new CommonServiceClient();
            //model.Id = ResultHelper.NewId;
            model.CreateTime = ResultHelper.NowTime;
            model.CreatePerson = GetUserId();
            if (model != null && ModelState.IsValid)
            {
                if (client.CreateModule(model,ref error)==1)
                {
                    LogHandler.WriteServiceLog(GetUserId(), "创建新模块 模块Id："+model.Id+" 模块名字："+model.Name, "成功", "创建", "模块维护");
                    return Json(JsonHandler.CreateMessage(1, Suggestion.InsertSucceed));
                }
                else
                {
                    LogHandler.WriteServiceLog(GetUserId(), "创建新模块 模块Id：" + model.Id + " 模块名字：" + model.Name, "失败", "创建", "模块维护");
                    return Json(JsonHandler.CreateMessage(0, Suggestion.InsertFail+" "+error.ErrorMessage));
                }
            }
            else
            {
                return Json(JsonHandler.CreateMessage(0, Suggestion.InsertFail));
            }
        }
        #endregion


        #region 创建
        [SupportFilter(ActionName = "Create")]
        public ActionResult CreateOpt(string moduleId)
        {
            ViewBag.Perm = GetPermission();
            SysModuleOperate sysModuleOptModel = new SysModuleOperate();
            sysModuleOptModel.ModuleId = moduleId;
            sysModuleOptModel.IsValid = true;
            return View(sysModuleOptModel);
        }


        [HttpPost]
        [SupportFilter(ActionName = "Create")]
        public JsonResult CreateOpt(SysModuleOperate info)
        {
            CommonServiceClient client = new CommonServiceClient();
            if (info != null && ModelState.IsValid)
            {
                SysModuleOperate entity = client.GetModuleOperateById(info.Id);
                if (entity != null)
                {
                    return Json(JsonHandler.CreateMessage(0, Suggestion.PrimaryRepeat), JsonRequestBehavior.AllowGet);
                }
                info.Id = info.ModuleId + info.KeyCode;

                if (client.CreateModuleOperate(info,ref error)==1)
                {
                    LogHandler.WriteServiceLog(GetUserId(), string.Format("新增模块操作码,模块ID:{0},操作码name:{1},操作码key:{2}",info.ModuleId,info.Name,info.KeyCode), "成功", "创建", "模块设置");
                    return Json(JsonHandler.CreateMessage(1, Suggestion.InsertSucceed), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    LogHandler.WriteServiceLog(GetUserId(), string.Format("新增模块操作码,模块ID:{0},操作码name:{1},操作码key:{2}", info.ModuleId, info.Name, info.KeyCode), "失败", "创建", "模块设置");
                    return Json(JsonHandler.CreateMessage(0, Suggestion.InsertFail+Environment.NewLine+error.ErrorMessage), JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(JsonHandler.CreateMessage(0, Suggestion.InsertFail), JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        #region 修改模块
        [SupportFilter]
        public ActionResult Edit(string id)
        {
            CommonServiceClient client = new CommonServiceClient();
            ViewBag.Perm = GetPermission();
            SysModule entity = client.GetModuleById(id);
            return View(entity);
        }

        [HttpPost]
        [SupportFilter]
        public JsonResult Edit(SysModule model)
        {
            CommonServiceClient client = new CommonServiceClient();
            if (model != null && ModelState.IsValid)
            {
                if (client.EditModule(model,ref error)==1)
                {
                    LogHandler.WriteServiceLog(GetUserId(), string.Format("修改模块,模块ID:{0},模块名称:{1}", model.Id,model.Name), "成功", "修改", "系统菜单");
                    return Json(JsonHandler.CreateMessage(1, Suggestion.EditSucceed));
                }
                else
                {
                    LogHandler.WriteServiceLog(GetUserId(), string.Format("修改模块,模块ID:{0},模块名称:{1}", model.Id, model.Name), "失败", "修改", "系统菜单");
                    return Json(JsonHandler.CreateMessage(0, Suggestion.EditFail+Environment.NewLine+error.ErrorMessage));
                }
            }
            else
            {
                return Json(JsonHandler.CreateMessage(0, Suggestion.EditFail));
            }
        }
        #endregion



        #region 删除
        [HttpPost]
        [SupportFilter]
        public JsonResult Delete(string id)
        {
            CommonServiceClient client = new CommonServiceClient();
            if (!string.IsNullOrWhiteSpace(id))
            {
                if (client.DeleteModule(id,ref error)==1)
                {
                    LogHandler.WriteServiceLog(GetUserId(), string.Format("删除模块,模块ID:{0}", id), "成功", "删除", "模块设置");
                    return Json(JsonHandler.CreateMessage(1, Suggestion.DeleteSucceed), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    LogHandler.WriteServiceLog(GetUserId(), string.Format("删除模块,模块ID:{0}", id), "失败", "删除", "模块设置");
                    return Json(JsonHandler.CreateMessage(0, Suggestion.DeleteFail+Environment.NewLine+error.ErrorMessage), JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(JsonHandler.CreateMessage(0, Suggestion.DeleteFail), JsonRequestBehavior.AllowGet);
            }


        }


        [HttpPost]
        [SupportFilter(ActionName = "Delete")]
        public JsonResult DeleteOpt(string id)
        {
            CommonServiceClient client = new CommonServiceClient();
            if (!string.IsNullOrWhiteSpace(id))
            {
                if (client.DeleteModuleOperateById(id,ref error)==1)
                {
                    LogHandler.WriteServiceLog(GetUserId(), string.Format("删除模块操作码,模块操作码ID:{0}", id), "成功", "删除", "模块设置KeyCode");
                    return Json(JsonHandler.CreateMessage(1, Suggestion.DeleteSucceed), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    LogHandler.WriteServiceLog(GetUserId(), string.Format("删除模块操作码,模块操作码ID:{0}", id), "失败", "删除", "模块设置KeyCode");
                    return Json(JsonHandler.CreateMessage(0, Suggestion.DeleteFail+Environment.NewLine+error.ErrorMessage), JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(JsonHandler.CreateMessage(0, Suggestion.DeleteFail), JsonRequestBehavior.AllowGet);
            }


        }

        #endregion


    }
}

CLZ.Solution/CLZ/Views/SysModule/Create.cshtml
@model CLZ.CLZService.SysModule
@using CLZ.Common;
@using CLZ.Core;
@using CLZ.Model.Sys;
@{
    ViewBag.Title = "创建";
    Layout = "~/Views/Shared/_Index_LayoutEdit.cshtml";
    List<permModel> perm = (List<permModel>)ViewBag.Perm;
    if (perm == null)
    {
        perm = new List<permModel>();
    }
}

<script type="text/javascript">
    $(function () {
        $("#btnSave").click(function () {
            if ($("#CreateForm").form('validate')) {
                $.ajax({
                    url: "@Url.Action("Create")",
                type: "Post",
                data: $("form").serialize(),
                dataType: "json",
                success: function (data) {
                    if (data.type == 1) {
                        window.parent.frameReturnByMes(data.message);
                        window.parent.frameReturnByReload(true);
                        window.parent.frameReturnByClose()
                    }
                    else {
                        window.parent.frameReturnByMes(data.message);
                    }
                }
            });
        }
        return false;
    });
    $("#btnReturn").click(function () {
        window.parent.frameReturnByClose();
    });

    $("#selectImage").click(function () {
        $("#imageContainer").show();
    });
    $("#imageContainer").mousemove(function (e) {
        var x = e.clientX - $("#imageContainer").offset().left;
        var y = e.clientY - $("#imageContainer").offset().top;
        var sc = $(this);
        var scH = sc.scrollTop()
        $("#position").text("x:" + x + "   y:" + y + "  scH:" + scH);
    }).click(function (e) {
        var sc = $(this);
        var scH = sc.scrollTop();
        var x = e.clientX - $("#imageContainer").offset().left;
        var y = e.clientY - $("#imageContainer").offset().top + scH;
        var row = parseInt(x / 16);
        var col = parseInt(y / 16);
        var index = 25 * col + row + 1;
        var imgClass = "pic_" + index;
        //$("#position").text("index:" + imgClass);
        $("#icon").removeClass().addClass(imgClass);
        $("#imageContainer").hide();
        $("#Iconic").val(imgClass);
    });
});
</script>
<div class="mvctool bgb">
    @Html.ToolButton("btnSave", "icon-save", "保存", perm, "Save", true)
    @Html.ToolButton("btnReturn", "icon-return", "返回", false)
</div>
@using (Html.BeginForm("Create", "SysModule", null, FormMethod.Post, new { Id = "CreateForm" }))
{
    @Html.HiddenFor(model => model.CreateTime)
    <table class="fromEditTable setTextWidth300">
        <tbody>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.Id)：
                </td>
                <td style="width:310px">
                    @Html.EditorFor(model => model.Id)
                </td>
                <td>@Html.ValidationMessageFor(model => model.Id)</td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.Name)：
                </td>
                <td style="width:310px">
                    @Html.EditorFor(model => model.Name)
                </td>
                <td>@Html.ValidationMessageFor(model => model.Name)</td>
            </tr>

            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.ParentId)：
                </td>
                <td style="width:310px">
                    @Html.EditorFor(model => model.ParentId)
                </td>
                <td>@Html.ValidationMessageFor(model => model.ParentId)</td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.Url)：
                </td>
                <td style="width:310px">
                    @Html.EditorFor(model => model.Url)
                </td>
                <td>@Html.ValidationMessageFor(model => model.Url)</td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.Iconic)：
                </td>
                @{
                     string icon ="";
                }
                <td style="width:310px;">
                    @Html.HiddenFor(model => model.Iconic)
                    <div id="icon" class="@icon"></div><a href="#" id="selectImage" class="easyui-linkbutton" style="position:absolute;margin-top:-20px;margin-left:20px;">选择</a>
                    <div id="imageContainer" style="width: 420px; height: 200px; display:none; overflow:auto;position:absolute;margin-top:10px;"><img src="/Content/Images/icon.png" /></div>
                </td>
                <td>@Html.ValidationMessageFor(model => model.Iconic)</td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.Sort)：
                </td>
                <td style="width:310px">
                    @Html.EditorFor(model => model.Sort)
                </td>
                <td>@Html.ValidationMessageFor(model => model.Sort)</td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.Remark)：
                </td>
                <td style="width:310px">
                    @Html.EditorFor(model => model.Remark)
                </td>
                <td>@Html.ValidationMessageFor(model => model.Remark)</td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.Enable)：
                </td>
                <td style="width:310px">
                    @{
                        bool isEnable = @Model.Enable == null ? false : true;
                    }
                    @Html.CheckBox("Enable",isEnable)
                </td>
                <td>@Html.ValidationMessageFor(model => model.Enable)</td>
            </tr>

            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.IsLast)：
                </td>
                <td style="width:310px">
                    @Html.CheckBoxFor(model => model.IsLast, new { @checked = true })
                </td>
                <td>@Html.ValidationMessageFor(model => model.IsLast)</td>
            </tr>

        </tbody>
    </table>
}

CLZ.Solution/CLZ/Views/SysModule/CreateOpt.cshtml
@model CLZ.CLZService.SysModuleOperate
@using CLZ.Common;
@using CLZ.Core;
@using CLZ.Model.Sys;
@{
    ViewBag.Title = "创建";
    Layout = "~/Views/Shared/_Index_LayoutEdit.cshtml";
    List<permModel> perm = (List<permModel>)ViewBag.Perm;
    if (perm == null)
    {
        perm = new List<permModel>();
    }
}

<script type="text/javascript">
    $(function () {
        $("#btnSave").click(function () {
            if ($("#CreateForm").form('validate')) {
                $.ajax({
                url: "@Url.Action("CreateOpt")",
                type: "Post",
                data: $("form").serialize(),
                dataType: "json",
                success: function (data) {
                    if (data.type == 1) {
                        window.parent.frameReturnByMes(data.message);
                        window.parent.frameReturnByReloadOpt(true);
                        window.parent.frameReturnByClose()
                    }
                    else {
                        window.parent.frameReturnByMes(data.message);
                    }
                }
            });
        }
        return false;
    });
    $("#btnReturn").click(function () {
        window.parent.frameReturnByClose();
    });
});
</script>
<div class="mvctool bgb">
    @Html.ToolButton("btnSave", "icon-save", "保存", perm, "Save", true)
    @Html.ToolButton("btnReturn", "icon-return", "返回", false)
</div>
@using (Html.BeginForm("Create", "SysModule", null, FormMethod.Post, new { Id = "CreateForm" }))
{
    @Html.HiddenFor(model => model.Id)
    <table class="fromEditTable setTextWidth300">
        <tbody>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.Name)：
                </td>
                <td style="width:310px">
                    @Html.EditorFor(model => model.Name)
                </td>
                <td>@Html.ValidationMessageFor(model => model.Name)</td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.KeyCode)：
                </td>
                <td style="width:310px">
                    @Html.EditorFor(model => model.KeyCode)
                </td>
                <td>@Html.ValidationMessageFor(model => model.KeyCode)</td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.ModuleId)：
                </td>
                <td style="width:310px">
                    @Html.TextBoxFor(model => model.ModuleId, new { @readOnly = "readOnly" })
                </td>
                <td>@Html.ValidationMessageFor(model => model.ModuleId)</td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.IsValid)：
                </td>
                <td style="width:310px">
                    @Html.CheckBoxFor(model => model.IsValid, new { @checked = true })
                </td>
                <td>@Html.ValidationMessageFor(model => model.IsValid)</td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.Sort)：
                </td>
                <td style="width:310px">
                    @Html.EditorFor(model => model.Sort)
                </td>
                <td>@Html.ValidationMessageFor(model => model.Sort)</td>
            </tr>
        </tbody>
    </table>
}

CLZ.Solution/CLZ/Views/SysModule/Edit.cshtml
@model CLZ.CLZService.SysModule
@using CLZ.Common;
@using CLZ.Core;
@using CLZ.Model.Sys;

@{
    ViewBag.Title = "修改";
    Layout = "~/Views/Shared/_Index_LayoutEdit.cshtml";
    List<permModel> perm = (List<permModel>)ViewBag.Perm;
    if (perm == null)
    {
        perm = new List<permModel>();
    }
}

<script type="text/javascript">
$(function () {
    $("#btnSave").click(function () {
        if ($("#EditForm").form('validate')) {
            $.ajax({
                url: "@Url.Action("Edit")",
                type: "Post",
                data: $("form").serialize(),
                dataType: "json",
                success: function (data) {
                    if (data.type == 1) {
                        window.parent.frameReturnByMes(data.message);
                        window.parent.frameReturnByReload(true);
                        window.parent.frameReturnByClose()
                    }
                    else {
                        window.parent.frameReturnByMes(data.message);
                    }
                }
            });
        }
        return false;
    });
    $("#btnReturn").click(function () {
         window.parent.frameReturnByClose();
    });

    $("#selectImage").click(function () {
        $("#imageContainer").show();
    });
    $("#imageContainer").mousemove(function (e) {
        var x = e.clientX - $("#imageContainer").offset().left;
        var y = e.clientY - $("#imageContainer").offset().top;
        var sc = $(this);
        var scH = sc.scrollTop()
        $("#position").text("x:"+x+"   y:"+y+"  scH:"+scH);
    }).click(function (e) {
        var sc = $(this);
        var scH = sc.scrollTop();
        var x = e.clientX - $("#imageContainer").offset().left;
        var y = e.clientY - $("#imageContainer").offset().top + scH;
        var row = parseInt(x / 16);
        var col = parseInt(y / 16);
        var index = 25 * col + row + 1;
        var imgClass = "pic_" + index;
        //$("#position").text("index:" + imgClass);
        $("#icon").removeClass().addClass(imgClass);
        $("#imageContainer").hide();
        $("#Iconic").val(imgClass);
    });

});
</script>

@*<div><label id="position"></label></div>*@
<div class="mvctool bgb">
    @Html.ToolButton("btnSave", "icon-save", "保存", perm, "Save", true)
    @Html.ToolButton("btnReturn", "icon-return", "返回", false)
</div>
@using (Html.BeginForm("Edit", "SysModule", null, FormMethod.Post, new { Id = "EditForm" }))
{
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.CreateTime)
    @Html.HiddenFor(model => model.CreatePerson)
    <table class="fromEditTable setTextWidth300">
        <tbody>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.Name)：
                </td>
                <td style="width:310px">
                    @Html.EditorFor(model => model.Name)
                </td>
                <td>@Html.ValidationMessageFor(model => model.Name)</td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.ParentId)：
                </td>
                <td style="width:310px">
                    @Html.EditorFor(model => model.ParentId)
                </td>
                <td>@Html.ValidationMessageFor(model => model.ParentId)</td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.Url)：
                </td>
                <td style="width:310px">
                    @Html.EditorFor(model => model.Url)
                </td>
                <td>@Html.ValidationMessageFor(model => model.Url)</td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.Iconic)：
                </td>
                @{
                    string icon = @Model.Iconic;
                }
                <td style="width:310px;">
                    @Html.HiddenFor(model => model.Iconic)
                    <div id="icon" class="@icon"></div><a href="#" id="selectImage" class="easyui-linkbutton" style="position:absolute;margin-top:-20px;margin-left:20px;">选择</a>
                    <div id="imageContainer" style="width: 420px; height: 200px; display:none; overflow:auto;position:absolute;margin-top:10px;"><img src="/Content/Images/icon.png" /></div>
                </td>
                <td>@Html.ValidationMessageFor(model => model.Iconic)</td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.Sort)：
                </td>
                <td style="width:310px">
                    @Html.EditorFor(model => model.Sort)
                </td>
                <td>@Html.ValidationMessageFor(model => model.Sort)</td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.Remark)：
                </td>
                <td style="width:310px">
                    @Html.EditorFor(model => model.Remark)
                </td>
                <td>@Html.ValidationMessageFor(model => model.Remark)</td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.Enable)：
                </td>
                <td style="width:310px">
                    @{
                        bool isEnable = @Model.Enable == null ? false : true;
                    }
                    @Html.CheckBox("Enable", isEnable)
                </td>
                <td>@Html.ValidationMessageFor(model => model.Enable)</td>
            </tr>

            <tr>
                <td style="width:100px; text-align:right;">
                    @Html.LabelFor(model => model.IsLast)：
                </td>
                <td style="width:310px">
                    @Html.CheckBoxFor(model => model.IsLast)
                </td>
                <td>@Html.ValidationMessageFor(model => model.IsLast)</td>
            </tr>

        </tbody>
    </table>
}