CLZ.Solution/CLZ/Controllers/SysUserController.cs
using CLZ.CLZService;
using CLZ.Common;
using CLZ.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CLZ.Controllers
{
    public class SysUserController : BaseController
    {
        [SupportFilter]
        public ActionResult Index()
        {
            ViewBag.Perm = GetPermission();
            return View();
        }


        [SupportFilter(ActionName = "Index")]
        public JsonResult GetList(GridPager pager, string queryStr)
        {
            ViewBag.Perm = GetPermission();
            CommonServiceClient client = new CommonServiceClient();
            List<SysUser> list = client.GetSysUserList(ref pager, queryStr);
            var json = new
            {
                total = pager.totalRows,
                rows = list

            };

            return Json(json);
        }

        #region 设置用户角色
        [SupportFilter(ActionName = "Allot")]
        public ActionResult GetRoleByUser(string userId)
        {
            ViewBag.UserId = userId;
            ViewBag.Perm = GetPermission();
            return View();
        }

        [SupportFilter(ActionName = "Allot")]
        public JsonResult GetRoleListByUser(GridPager pager, string userId)
        {
            CommonServiceClient client=new CommonServiceClient();
            if (string.IsNullOrWhiteSpace(userId))
                return Json(0);
            var userList = client.GetRoleByUserId(ref pager, userId);
            var jsonData = new
            {
                total = pager.totalRows,
                rows = (
                    from r in userList
                    select new
                    {
                        Id = r.Id,
                        Name = r.Name,
                        Description = r.Description,
                        Flag = r.flag == "0" ? "0" : "1",
                    }
                ).ToArray()
            };
            return Json(jsonData);
        }
        #endregion
        [SupportFilter(ActionName = "Save")]
        public JsonResult UpdateUserRoleByUserId(string userId, string roleIds)
        {
            CommonServiceClient client = new CommonServiceClient();
            string[] arr = roleIds.Split(',');


            if (client.UpdateSysRoleSysUser(userId, arr.ToList())>0)
            {
                LogHandler.WriteServiceLog(GetUserId(), "Ids:" + roleIds, "成功", "分配角色", "用户设置");
                return Json(JsonHandler.CreateMessage(1, Suggestion.SetSucceed), JsonRequestBehavior.AllowGet);
            }
            else
            {
                LogHandler.WriteServiceLog(GetUserId(), "Ids:" + roleIds, "失败", "分配角色", "用户设置");
                return Json(JsonHandler.CreateMessage(0, Suggestion.SetFail), JsonRequestBehavior.AllowGet);
            }

        }

        #region 创建
        [SupportFilter]
        public ActionResult Create()
        {
            ViewBag.Perm = GetPermission();
            return View();
        }

        [HttpPost]
        [SupportFilter]
        public JsonResult Create(SysUser model)
        {
            CommonServiceClient client = new CommonServiceClient();
            model.CreateTime = ResultHelper.NowTime;
            if (model != null && ModelState.IsValid)
            {
                model.CreatePerson = GetUserId();
                model.CreateTime = DateTime.Now;
                model.Password = ValueConvert.MD5("123456");
                model.State = true;
                if (client.CreateSysUser(model,ref error) == 1)
                {
                    LogHandler.WriteServiceLog(GetUserId(), string.Format("创建用户,用户Id:{0},用户Name:{1}", model.Id,model.UserName), "成功", "创建", "SysRole");
                    return Json(JsonHandler.CreateMessage(1, Suggestion.InsertSucceed));
                }
                else
                {
                    LogHandler.WriteServiceLog(GetUserId(), string.Format("创建用户,用户Id:{0},用户Name:{1}", model.Id, model.UserName), "失败", "创建", "SysRole");
                    return Json(JsonHandler.CreateMessage(0, Suggestion.InsertFail+Environment.NewLine+error.ErrorMessage));
                }
            }
            else
            {
                return Json(JsonHandler.CreateMessage(0, Suggestion.InsertFail));
            }
        }
        #endregion

    }
}

CLZ.Solution/CLZ/Views/SysUser/Create.cshtml
@model CLZ.CLZService.SysUser
@using CLZ.Common;
@using CLZ.Core;
@using CLZ.CLZService;
@{
    ViewBag.Title = "创建";
    Layout = "~/Views/Shared/_Index_LayoutEdit.cshtml";
}

<script type="text/javascript">
    $(function () {
        $("#btnSave").click(function () {
            if ($("#CreateForm").form('validate')) {
                $.ajax({
                    url: "/SysUser/Create",
                    type: "Post",
                    data: $("#CreateForm").serialize(),
                    dataType: "json",
                    success: function (data) {
                        if (data.type == 1) {
                            window.parent.frameReturnByMes(data.message);
                            window.parent.frameReturnByReload(true);
                            window.parent.frameReturnByClose()
                        }
                        else {
                            window.parent.frameReturnByMes("失败");
                        }
                    }
                });
            }
            else {
                //$.messageBox5s('提示','@Suggestion.ValidateFail' );
            }

        });
    });
</script>
<div class="mvctool bgb">
    <a id="btnSave" style="float: left;" class="l-btn l-btn-plain"><span class="l-btn-left"><span class="l-btn-text icon-save" style="padding-left: 20px;">保存</span></span></a>
</div>
@using (Html.BeginForm("Create", "SysUser", null, FormMethod.Post, new { Id = "CreateForm" }))
{
    <table class="fromEditTable setTextWidth300">
        <tbody>
            <tr>
                <td style="width:100px; text-align:right;">
                    用户ID：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.Id, new { data_options = "required:true" })
                </td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    用户姓名：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.UserName, new { data_options = "required:true" })
                </td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    所在部门：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.DepId, new { data_options = "required:true" })
                </td>
            </tr>
            <tr>
                <td style="width:100px; text-align:right;">
                    posid：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.PosId, new { data_options = "required:true" })
                </td>
            </tr>
        </tbody>
    </table>
}

CLZ.Solution/CLZ/Views/SysUser/GetRoleByUser.cshtml
@using CLZ.Common;
@using CLZ.Core;
@using CLZ.Model.Sys;
@{
    ViewBag.Title = "设置用户包含的角色";
    Layout = "~/Views/Shared/_Index_LayoutEdit.cshtml";

    List<permModel> perm = (List<permModel>)ViewBag.Perm;
    if (perm == null)
    {
        perm = new List<permModel>();
    }
}

<div class="mvctool bgb">
    @Html.ToolButton("btnSave", "icon-save", "保存", perm, "Create", true)
</div>
<div class="pd3">
    <table id="UserList"></table>
</div>
@*Jqgrid*@
<script type="text/javascript">
    $(function () {

        $('#UserList').datagrid({
            url: '/SysUser/GetRoleListByUser?userId=@(ViewBag.UserId)',
            width: SetGridWidthSub(6),
            methord: 'post',
            height: SetGridHeightSub(41),
            fitColumns: true,
            sortName: 'Id',
            sortOrder: 'desc',
            idField: 'Id',
            pageSize: 12,
            pageList: [12, 20, 30, 40, 50],
            pagination: true,
            striped: true, //奇偶行是否区分
            singleSelect: true,//单选模式
            columns: [[
                { field: 'Id', title: 'ID', width: 80, hidden: true },
                { field: 'Name', title: '角色名称', width: 120 },
                { field: 'Description', title: '说明', width: 80 },
                { field: 'Flag', title: '是否分配', width: 80, editor: { type: 'checkbox', options: { on: '1', off: '0' } } }
            ]],
            onLoadSuccess: function () {
                var rows = $("#UserList").datagrid("getRows");
                for (var i = 0; i < rows.length; i++) {
                    //获取每一行的数据
                    $('#UserList').datagrid('beginEdit', i);
                }
            }
        });
    });
</script>

@*operation*@
<script type="text/javascript">
    $(function () {
        $("#btnSave").click(function () {

            var rows = $("#UserList").datagrid("getRows"); //这段代码是获取当前页的所有行。
            var data = new Array();
            for (var i = 0; i < rows.length; i++) {
                var setFlag = $("td[field='Flag'] input").eq(i).prop("checked");
                if (setFlag)//判断是否有作修改
                {
                    data.push(rows[i].Id);
                }
            }
            var roleIds = data.join();
            //提交数据库
            $.post("/SysUser/UpdateUserRoleByUserId", { userId: '@(ViewBag.UserId)', roleIds: roleIds },
             function (data) {
                 if (data.type == 1) {
                     window.parent.frameReturnByMes(data.message);
                     window.parent.frameReturnByReload(true);
                     window.parent.frameReturnByClose()
                 }
                 else {
                     window.parent.frameReturnByMes(data.message);
                 }
             }, "json");
        });

    });
</script>

CLZ.Solution/CLZ/Views/SysUser/Index.cshtml
@using CLZ.Core;
@using CLZ.Common;
@using CLZ.Model.Sys;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Index_Layout.cshtml";

    List<permModel> perm = (List<permModel>)ViewBag.Perm;
    if (perm == null)
    {
        perm = new List<permModel>();
    }
}
<div class="mvctool">
    <input id="txtQuery" type="text" class="searchText" />
    @Html.ToolButton("btnQuery", "icon-search", "查询", perm, "Query", true)
    @Html.ToolButton("btnCreate", "icon-add", "新增", perm, "Create", true)
    @Html.ToolButton("btnEdit", "icon-edit", "编辑", perm, "Edit", true)
    @Html.ToolButton("btnDetails", "icon-details", "详细", perm, "Details", true)
    @Html.ToolButton("btnDelete", "icon-remove", "删除", perm, "Delete", true)
    @Html.ToolButton("btnAllot", "icon-share", "分配角色", perm, "Allot", true)

</div>
<div id="modalwindow" class="easyui-window" data-options="modal:true,closed:true,minimizable:false,shadow:false"></div>
<table id="List"></table>
<script type="text/javascript">
    $(function () {
        $('#List').datagrid({
            url: '@Url.Action("GetList")',
            width: $(window).width() - 10,
            methord: 'post',
            height: $(window).height() - 35,
            fitColumns: true,
            sortName: 'CreateTime',
            sortOrder: 'desc',
            idField: 'Id',
            pageSize: 15,
            pageList: [15, 20, 30, 40, 50],
            pagination: true,
            striped: true, //奇偶行是否区分
            singleSelect: true,//单选模式
            //rownumbers: true,//行号
            columns: [[
                { field: 'Id', title: 'ID', width: 80, sortable: true },
                { field: 'UserName', title: '用户姓名', width: 80, sortable: true },
                { field: 'Password', title: '密码', width: 80, sortable: true },
                { field: 'DepId', title: '部门ID', width: 80, sortable: true },
                { field: 'PosId', title: 'PosId', width: 80, sortable: true }
            ]]
        });
     });
    //ifram 返回
    function frameReturnByClose() {
        $("#modalwindow").window('close');
    }
    function frameReturnByReload(flag) {
        if (flag)
            $("#List").datagrid('load');
        else
            $("#List").datagrid('reload');
    }
    function frameReturnByMes(mes) {
        $.messageBox5s('提示', mes);
    }
    $(function () {
        $("#btnExport").click(function () {
            $("#modalwindow").html("<iframe width='100%' height='98%' scrolling='no' frameborder='0'' src='/SysHelper/ReportControl'></iframe>");
            $("#modalwindow").window({ title: '导出', width: 320, height: 200, iconCls: 'icon-add' }).window('open');
        });
        $("#btnCreate").click(function () {
            $("#modalwindow").html("<iframe width='100%' height='98%' scrolling='no' frameborder='0'' src='/SysUser/Create'></iframe>");
            $("#modalwindow").window({ title: '新增', width: 700, height: 400, iconCls: 'icon-add' }).window('open');
        });
        $("#btnEdit").click(function () {
            var row = $('#List').datagrid('getSelected');
            if (row != null) {
                $("#modalwindow").html("<iframe width='100%' height='99%'  frameborder='0' src='/SysUser/Edit?id=" + row.Id + "&Ieguid=" + GetGuid() + "'></iframe>");
                $("#modalwindow").window({ title: '编辑', width: 700, height: 430, iconCls: 'icon-edit' }).window('open');
            } else { $.messageBox5s('提示', '@Suggestion.PlaseChooseToOperatingRecords'); }
        });
        $("#btnDetails").click(function () {
            var row = $('#List').datagrid('getSelected');
            if (row != null) {
                $("#modalwindow").html("<iframe width='100%' height='98%' scrolling='no' frameborder='0' src='/SysUser/Details?id=" + row.Id + "&Ieguid=" + GetGuid() + "'></iframe>");
                $("#modalwindow").window({ title: '详细', width: 500, height: 300, iconCls: 'icon-details' }).window('open');
            } else { $.messageBox5s('提示', '@Suggestion.PlaseChooseToOperatingRecords'); }
        });
        $("#btnQuery").click(function () {
            var queryStr = $("#txtQuery").val();
            if (queryStr == null) {
                queryStr = "%";
            }
            $('#List').datagrid({
                url: '@Url.Action("GetList")?queryStr=' + encodeURI(queryStr)
            });

        });
        $("#btnDelete").click(function () {
            var row = $('#List').datagrid('getSelected');
            if (row != null) {
                $.messager.confirm('提示', '@Suggestion.YouWantToDeleteTheSelectedRecords', function (r) {
                    if (r) {
                        $.post("@Url.Action("Delete")?id=" + row.Id, function (data) {
                                if (data.type == 1)
                                    $("#List").datagrid('load');
                                $.messageBox5s('提示', data.message);
                            }, "json");

                        }
                });
                } else { $.messageBox5s('提示', '@Suggestion.PlaseChooseToOperatingRecords'); }
        });
        $("#btnAllot").click(function () {
            var row = $('#List').datagrid('getSelected');
            if (row != null) {

                $("#modalwindow").html("<iframe width='100%'  height='100%' scrolling='auto' frameborder='0' src='/SysUser/GetRoleByUser?userId=" + row.Id +  "'></iframe>");
                $("#modalwindow").window({ title: '分配角色', width: 720, height: 400, iconCls: 'icon-edit' }).window('open');
            } else { $.messageBox5s('提示', '@Suggestion.PlaseChooseToOperatingRecords'); }
        });
    });
</script>
@Html.Partial("~/Views/Shared/_Partial_AutoGrid.cshtml")